2023-05-26 13:13:32,933 INFO: Medication tracker startup [in /home/erica/portfolio/medication_tracker/app/__init__.py:61]
2023-05-26 13:14:14,473 INFO: Medication tracker startup [in /home/erica/portfolio/medication_tracker/app/__init__.py:61]
2023-05-26 13:16:07,930 INFO: Medication tracker startup [in /home/erica/portfolio/medication_tracker/app/__init__.py:61]
2023-05-26 13:22:12,417 INFO: Medication tracker startup [in /home/erica/portfolio/medication_tracker/app/__init__.py:61]
2023-05-26 13:22:15,724 ERROR: Exception on /user/Mortimer/manage_medications [GET] [in /home/erica/.local/lib/python3.10/site-packages/flask/app.py:1741]
Traceback (most recent call last):
  File "/home/erica/.local/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/erica/.local/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/erica/.local/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/erica/.local/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/erica/.local/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/erica/portfolio/medication_tracker/app/main/routes.py", line 39, in manage_medications
    medications = current_user.medication_list().all().asc()
AttributeError: 'list' object has no attribute 'asc'
2023-05-26 13:23:28,689 INFO: Medication tracker startup [in /home/erica/portfolio/medication_tracker/app/__init__.py:61]
2023-05-26 13:23:33,138 ERROR: Exception on /user/Mortimer/manage_medications [GET] [in /home/erica/.local/lib/python3.10/site-packages/flask/app.py:1741]
Traceback (most recent call last):
  File "/home/erica/.local/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/erica/.local/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/erica/.local/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/erica/.local/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/erica/.local/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/erica/portfolio/medication_tracker/app/main/routes.py", line 73, in manage_medications
    return render_template('manage_medications.html', title="Manage Medications", user=user, medications=medications, form=form)
  File "/home/erica/.local/lib/python3.10/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
  File "/home/erica/.local/lib/python3.10/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
  File "/home/erica/.local/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/erica/.local/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/erica/portfolio/medication_tracker/app/templates/manage_medications.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/erica/portfolio/medication_tracker/app/templates/base.html", line 35, in top-level template code
    {% block content %}{% endblock %}
  File "/home/erica/portfolio/medication_tracker/app/templates/manage_medications.html", line 34, in block 'content'
    {% for medication in medications %}
TypeError: 'NoneType' object is not iterable
2023-05-26 13:24:38,325 INFO: Medication tracker startup [in /home/erica/portfolio/medication_tracker/app/__init__.py:61]
2023-05-26 13:25:14,048 INFO: Medication tracker startup [in /home/erica/portfolio/medication_tracker/app/__init__.py:61]
2023-05-26 13:29:48,486 INFO: Medication tracker startup [in /home/erica/portfolio/medication_tracker/app/__init__.py:61]
2023-05-26 13:33:12,830 INFO: Medication tracker startup [in /home/erica/portfolio/medication_tracker/app/__init__.py:61]
2023-05-26 13:33:42,126 INFO: Medication tracker startup [in /home/erica/portfolio/medication_tracker/app/__init__.py:61]
2023-05-26 13:41:09,572 INFO: Medication tracker startup [in /home/erica/portfolio/medication_tracker/app/__init__.py:61]
2023-05-26 14:04:54,515 INFO: Medication tracker startup [in /home/erica/portfolio/medication_tracker/app/__init__.py:61]
2023-05-26 14:10:01,368 INFO: Medication tracker startup [in /home/erica/portfolio/medication_tracker/app/__init__.py:61]
2023-05-26 14:21:49,018 INFO: Medication tracker startup [in /home/erica/portfolio/medication_tracker/app/__init__.py:61]
2023-05-26 14:22:21,592 INFO: Medication tracker startup [in /home/erica/portfolio/medication_tracker/app/__init__.py:61]
2023-05-26 14:24:32,265 INFO: Medication tracker startup [in /home/erica/portfolio/medication_tracker/app/__init__.py:61]
2023-05-26 14:25:02,827 INFO: Medication tracker startup [in /home/erica/portfolio/medication_tracker/app/__init__.py:61]
2023-05-26 14:25:37,302 INFO: Medication tracker startup [in /home/erica/portfolio/medication_tracker/app/__init__.py:61]
2023-05-26 14:26:42,198 INFO: Medication tracker startup [in /home/erica/portfolio/medication_tracker/app/__init__.py:61]
2023-05-26 14:26:56,525 INFO: Medication tracker startup [in /home/erica/portfolio/medication_tracker/app/__init__.py:61]
2023-05-26 14:31:45,501 INFO: Medication tracker startup [in /home/erica/portfolio/medication_tracker/app/__init__.py:61]
2023-05-26 14:33:14,057 INFO: Medication tracker startup [in /home/erica/portfolio/medication_tracker/app/__init__.py:61]
2023-05-26 14:57:09,773 INFO: Medication tracker startup [in /home/erica/portfolio/medication_tracker/app/__init__.py:61]
2023-05-26 14:59:03,783 INFO: Medication tracker startup [in /home/erica/portfolio/medication_tracker/app/__init__.py:61]
2023-05-26 15:04:09,814 INFO: Medication tracker startup [in /home/erica/portfolio/medication_tracker/app/__init__.py:61]
2023-05-26 15:04:42,474 INFO: Medication tracker startup [in /home/erica/portfolio/medication_tracker/app/__init__.py:61]
2023-05-26 15:05:43,087 INFO: Medication tracker startup [in /home/erica/portfolio/medication_tracker/app/__init__.py:61]
2023-05-26 15:06:06,361 INFO: Medication tracker startup [in /home/erica/portfolio/medication_tracker/app/__init__.py:61]
2023-05-26 15:08:39,032 INFO: Medication tracker startup [in /home/erica/portfolio/medication_tracker/app/__init__.py:61]
2023-05-26 15:09:09,590 INFO: Medication tracker startup [in /home/erica/portfolio/medication_tracker/app/__init__.py:61]
2023-05-26 15:09:59,512 INFO: Medication tracker startup [in /home/erica/portfolio/medication_tracker/app/__init__.py:61]
2023-05-26 15:10:08,615 ERROR: Exception on /user/Mortimer/doctor/8 [POST] [in /home/erica/.local/lib/python3.10/site-packages/flask/app.py:1741]
Traceback (most recent call last):
  File "/home/erica/.local/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/erica/.local/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/erica/.local/lib/python3.10/site-packages/flask/app.py", line 1842, in finalize_request
    response = self.make_response(rv)
  File "/home/erica/.local/lib/python3.10/site-packages/flask/app.py", line 2134, in make_response
    raise TypeError(
TypeError: The view function for 'main.doctor' did not return a valid response. The function either returned None or ended without a return statement.
2023-05-26 15:11:38,114 INFO: Medication tracker startup [in /home/erica/portfolio/medication_tracker/app/__init__.py:61]
2023-05-26 15:13:32,518 INFO: Medication tracker startup [in /home/erica/portfolio/medication_tracker/app/__init__.py:61]
2023-05-26 15:16:44,966 INFO: Medication tracker startup [in /home/erica/portfolio/medication_tracker/app/__init__.py:61]
2023-05-26 15:19:43,232 INFO: Medication tracker startup [in /home/erica/portfolio/medication_tracker/app/__init__.py:61]
2023-05-26 15:22:18,920 INFO: Medication tracker startup [in /home/erica/portfolio/medication_tracker/app/__init__.py:61]
2023-05-26 15:24:44,603 INFO: Medication tracker startup [in /home/erica/portfolio/medication_tracker/app/__init__.py:61]
2023-05-26 15:24:59,371 ERROR: Exception on /user/Mortimer/doctor/2/edit [POST] [in /home/erica/.local/lib/python3.10/site-packages/flask/app.py:1741]
Traceback (most recent call last):
  File "/home/erica/.local/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/erica/.local/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/erica/.local/lib/python3.10/site-packages/flask/app.py", line 1842, in finalize_request
    response = self.make_response(rv)
  File "/home/erica/.local/lib/python3.10/site-packages/flask/app.py", line 2134, in make_response
    raise TypeError(
TypeError: The view function for 'main.edit_doctor' did not return a valid response. The function either returned None or ended without a return statement.
2023-05-26 15:25:40,520 INFO: Medication tracker startup [in /home/erica/portfolio/medication_tracker/app/__init__.py:61]
2023-05-26 15:39:02,813 INFO: Medication tracker startup [in /home/erica/portfolio/medication_tracker/app/__init__.py:61]
2023-05-26 15:40:50,959 INFO: Medication tracker startup [in /home/erica/portfolio/medication_tracker/app/__init__.py:61]
2023-05-26 15:41:48,982 INFO: Medication tracker startup [in /home/erica/portfolio/medication_tracker/app/__init__.py:61]
